namespace Maidsweeper.Core.Models;

public enum TileOwner
{
    Player,
    Rival,
    Neutral,
    Noble
}

public enum GameStatus
{
    Playing,
    Won,
    Lost
}

public enum GamePhase
{
    Playing,
    CardReward,
    UpgradeReward,
    FloorComplete,
    CampaignVictory
}

public enum UpgradeType
{
    Enhance,
    BonusSpoon,
    RemoveCard
}

public enum PlayerType
{
    Player,
    Rival
}

public enum CardEffectType
{
    Spritz,      // Is it safe or dangerous?
    Recall,      // Bag-draw clue pips (Recall - Imperious, Recall - Vague, etc.)
    Scurry,      // Reveal the safer tile
    Tingle,      // Sense a random rival/noble tile
    Twirl,       // Gain copper
    Brush,       // 3x3 area: annotate to exclude a random non-owner
    Sweep,       // 5x5 area: remove ExtraDirty
    Caffeinate,  // Gain 2 spoons (exhaust)
    Breathe,     // Draw 3 cards
    LockIn,      // Draw 2 cards (exhaust, free)
    Rendezvous,  // Reveal random player+rival tiles with swapped adjacency

    // --- Stage 3 cards ---
    Argue,       // 3x3 area: find and annotate neutrals
    AcceptHelp,  // Burst-1-cross: reveal safest type
    Eavesdrop,   // Single tile: learn owner without revealing
    Peek,        // Burst-1-cross: find nobles (conditional exhaust)
    Explode,     // Destroy a tile (Complaints + Mollify)
    Deliver,     // Convert noble to neutral, reveal safely
    Brat,        // Unreveal a revealed tile (exhaust)
    Ramble,      // Add Distraction stacks to rival
    Glaze,       // Gain Excuses stack (noble protection)
    Mask,        // Play another card for free (exhaust both)
    Nap,         // Retrieve card from exhaust pile
    Mollify      // Reduce Complaints by 1 (generated by Explode)
}

public enum SpecialTileType
{
    ExtraDirty
}

public enum AdjacencyRule
{
    King,       // 8-directional (default)
    Manhattan2  // All positions within Manhattan distance ≤ 2 (up to 12 neighbors)
}
