namespace Maidsweeper.Core.Models;

public enum TileOwner
{
    Player,
    Rival,
    Neutral,
    Noble
}

public enum GameStatus
{
    Playing,
    Won,
    Lost
}

public enum GamePhase
{
    Playing,
    CardReward,
    UpgradeReward,
    EquipmentReward,
    Shop,
    FloorComplete,
    CampaignVictory
}

public enum ShopSlotKind
{
    RegularCard,
    BonusSpoonCard,
    EnhancedCard,
    Equipment,
    RemoveCard,
    VisitingBunny,
    Enhance
}

public enum UpgradeType
{
    Enhance,
    BonusSpoon,
    RemoveCard
}

public enum PlayerType
{
    Player,
    Rival
}

public enum CardEffectType
{
    Spritz,      // Is it safe or dangerous?
    Recall,      // Bag-draw clue pips (Recall - Imperious, Recall - Vague, etc.)
    Scurry,      // Reveal the safer tile
    Tingle,      // Sense a random rival/noble tile
    Twirl,       // Gain copper
    Brush,       // 3x3 area: annotate to exclude a random non-owner
    Sweep,       // 5x5 area: remove ExtraDirty
    Caffeinate,  // Gain 2 spoons (exhaust)
    Breathe,     // Draw 3 cards
    LockIn,      // Draw 2 cards (exhaust, free)
    Rendezvous,  // Reveal random player+rival tiles with swapped adjacency

    // --- Stage 3 cards ---
    Argue,       // 3x3 area: find and annotate neutrals
    AcceptHelp,  // Burst-1-cross: reveal safest type
    Eavesdrop,   // Single tile: learn owner without revealing
    Peek,        // Burst-1-cross: find nobles (conditional exhaust)
    Explode,     // Destroy a tile (Complaints + Mollify)
    Deliver,     // Convert noble to neutral, reveal safely
    Brat,        // Unreveal a revealed tile (exhaust)
    Ramble,      // Add Distraction stacks to rival
    Glaze,       // Gain Excuses stack (noble protection)
    Mask,        // Play another card for free (exhaust both)
    Nap,         // Retrieve card from exhaust pile
    Mollify,     // Reduce Complaints by 1 (generated by Explode)

    // --- Stage 4 food cards ---
    Read,        // +1 card draw per turn for N floors
    Hydrate,     // +1 spoon on copper-granting player reveals for N floors
    Adopt,       // Reveal 1 random player tile at floor start for N floors

    // --- Stage 4 Recall variants ---
    RecallVague,     // Broader but weaker clue pips (5 targets, 8 draws)
    RecallSarcastic  // Anti-pips showing where tiles probably AREN'T yours
}

public enum SpecialTileType
{
    ExtraDirty
}

public enum AdjacencyRule
{
    King,       // 8-directional (default)
    Manhattan2  // All positions within Manhattan distance ≤ 2 (up to 12 neighbors)
}

public enum EquipmentEffectType
{
    // --- Stage 4 Set 1 (simple passives, M30) ---
    Coffee,        // +1 max spoon, -1 card draw (except turn 1)
    FrillyDress,   // First 4 neutral reveals on turn 1 don't end turn
    DustBunny,     // Reveal 1 random player tile at floor start
    Handbag,       // Draw +2 cards on first turn
    Eyeshadow,     // +1 Distraction stack at turn start
    Glasses,       // Free Tingle effect at turn start

    // --- Stage 4 Set 2 (deck modifiers, M31) ---
    Bleach,        // Enhance all Spritz/Sweep/Brush in deck (and future ones)
    Estrogen,      // Replace 3 random non-enhanced cards with bonus-spoon versions
    Progesterone,  // Replace 3 random non-bonus-spoon cards with enhanced versions
    CrystalBall,   // Add 3 doubly-upgraded Tingles to persistent deck
    Boots,         // Replace 1 random card with a doubly-upgraded reward card
    Tiara          // Double all copper rewards
}
